// Package outbound builds and dispatches helpdesk reply emails. The
// builder produces an RFC-822 message with the threading headers
// (In-Reply-To, References) that let the customer's mail client
// thread the reply onto the original conversation; the Sender
// dispatches it via an SMTP transport and persists the per-message
// row to email_messages so subsequent customer replies thread back
// to the ticket via the resolver's lookup.
//
// Scope:
//
//   - Builder is plain-text + optional HTML alternative. No
//     attachments yet (the agent UI's attachment-on-reply flow
//     lands in a follow-up PR; this PR's attachment surface is
//     inbound-only).
//   - Sender depends on a `Transport` interface so SMTP, an
//     in-memory fake (smtptest), and tests-with-Mailpit all
//     plug in. Production wires the existing notifications.SMTPAdapter
//     (or an upgraded multi-tenant variant when Surface F lands).
//   - DKIM signing is OUT of scope for this commit — the relay's
//     own DKIM keys still apply, and per-tenant DKIM is a tenant-
//     mailbox setting that lands with Surface F.
package outbound

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net/mail"
	"strings"
	"time"
)

// Message is the source-of-truth shape that the builder consumes.
// All fields are required EXCEPT InReplyTo / References / HTMLBody:
//
//   - From / To: RFC-5322 addresses. From is the helpdesk-side
//     reply mailbox (per-tenant; falls back to the global system
//     mailbox until Surface F adds the per-tenant override).
//   - Subject: typically "Re: <original subject>". The builder
//     does NOT prepend "Re:" on its own — that's the caller's
//     decision because some locales prefer "AW:", "回覆:", etc.
//   - InReplyTo: the original (or last-in-thread) Message-ID.
//     Without angle brackets — the builder adds them.
//   - References: the full ancestor chain, oldest first. The
//     builder formats it as a single space-separated header
//     value, brackets added per entry.
//   - BodyText: required. Plain-text version.
//   - HTMLBody: optional. When set, the builder emits a
//     multipart/alternative envelope with text first (RFC 2046
//     §5.1.4 — last part is most-preferred, so HTML last for
//     mail clients that render the first part by default).
type Message struct {
	From       string
	To         []string
	Cc         []string
	Subject    string
	InReplyTo  string
	References []string
	BodyText   string
	HTMLBody   string

	// Headers carries any extra headers the caller wants to
	// attach (X-Helpdesk-Ticket-ID, X-Helpdesk-Tenant-ID, etc).
	// The builder writes them in insertion order after the
	// fixed headers, BEFORE the body separator.
	Headers []Header
}

// Header is a (Name, Value) pair the builder writes as-is. Names
// are not canonicalised — the caller is responsible for picking
// Title-Case.
type Header struct {
	Name  string
	Value string
}

// Built is the result of Build: the wire bytes plus the
// generated Message-ID (which the caller persists to email_messages
// so the customer's reply threading lookup hits).
type Built struct {
	MessageID string
	Wire      []byte
}

// Build produces the RFC-822 wire bytes for m. Returns an error if
// any required field is missing.
//
// The Message-ID is generated by the builder when the caller does
// not supply one — every outbound message needs a unique ID so the
// inbound threading resolver can match a customer's reply (via
// In-Reply-To) back to this outbound message and onto the ticket.
//
// The generated ID is content-independent (random) so identical
// payloads (e.g. a "received your message" autoresponder sent to
// the same address twice) get distinct IDs. This is intentional
// — message-ID is identity, not a content hash.
func Build(now func() time.Time, m Message, messageIDDomain string) (Built, error) {
	if m.From == "" {
		return Built{}, errors.New("outbound: From required")
	}
	if _, err := mail.ParseAddress(m.From); err != nil {
		return Built{}, fmt.Errorf("outbound: From invalid: %w", err)
	}
	if len(m.To) == 0 {
		return Built{}, errors.New("outbound: To required")
	}
	for _, to := range m.To {
		if _, err := mail.ParseAddress(to); err != nil {
			return Built{}, fmt.Errorf("outbound: To invalid (%q): %w", to, err)
		}
	}
	if strings.TrimSpace(m.Subject) == "" {
		return Built{}, errors.New("outbound: Subject required")
	}
	if strings.TrimSpace(m.BodyText) == "" {
		return Built{}, errors.New("outbound: BodyText required")
	}
	if strings.TrimSpace(messageIDDomain) == "" {
		return Built{}, errors.New("outbound: message-id domain required")
	}

	msgID, err := generateMessageID(messageIDDomain)
	if err != nil {
		return Built{}, fmt.Errorf("outbound: generate message-id: %w", err)
	}

	var b strings.Builder
	b.Grow(len(m.BodyText) + len(m.HTMLBody) + 1024)

	writeHeader(&b, "From", m.From)
	writeHeader(&b, "To", strings.Join(m.To, ", "))
	if len(m.Cc) > 0 {
		writeHeader(&b, "Cc", strings.Join(m.Cc, ", "))
	}
	writeHeader(&b, "Subject", m.Subject)
	writeHeader(&b, "Date", now().UTC().Format(time.RFC1123Z))
	writeHeader(&b, "Message-ID", "<"+msgID+">")

	if m.InReplyTo != "" {
		writeHeader(&b, "In-Reply-To", "<"+strings.Trim(m.InReplyTo, "<>")+">")
	}
	if len(m.References) > 0 {
		writeHeader(&b, "References", formatReferences(m.References))
	}

	for _, h := range m.Headers {
		writeHeader(&b, h.Name, h.Value)
	}

	writeHeader(&b, "MIME-Version", "1.0")

	switch {
	case m.HTMLBody != "":
		// multipart/alternative — text first, HTML last so
		// modern clients (which render the LAST acceptable
		// part) get HTML. The boundary is a random hex
		// string to avoid collision with body content.
		boundary, err := generateBoundary()
		if err != nil {
			return Built{}, fmt.Errorf("outbound: generate boundary: %w", err)
		}
		writeHeader(&b, "Content-Type", `multipart/alternative; boundary="`+boundary+`"`)
		b.WriteString("\r\n")

		// Plain-text part.
		b.WriteString("--" + boundary + "\r\n")
		b.WriteString("Content-Type: text/plain; charset=\"utf-8\"\r\n")
		b.WriteString("Content-Transfer-Encoding: 8bit\r\n")
		b.WriteString("\r\n")
		b.WriteString(normaliseBodyEOL(m.BodyText))
		b.WriteString("\r\n")

		// HTML part.
		b.WriteString("--" + boundary + "\r\n")
		b.WriteString("Content-Type: text/html; charset=\"utf-8\"\r\n")
		b.WriteString("Content-Transfer-Encoding: 8bit\r\n")
		b.WriteString("\r\n")
		b.WriteString(normaliseBodyEOL(m.HTMLBody))
		b.WriteString("\r\n")

		// Final boundary.
		b.WriteString("--" + boundary + "--\r\n")

	default:
		// Plain text only.
		writeHeader(&b, "Content-Type", "text/plain; charset=\"utf-8\"")
		writeHeader(&b, "Content-Transfer-Encoding", "8bit")
		b.WriteString("\r\n")
		b.WriteString(normaliseBodyEOL(m.BodyText))
	}

	return Built{
		MessageID: msgID,
		Wire:      []byte(b.String()),
	}, nil
}

// writeHeader emits one RFC-822 header line. Continuation folding
// (for headers > 78 cols) is the caller's responsibility — we keep
// it simple and trust the inputs to be short. Subjects with very
// long content are silently passed through; modern MTAs accept
// long lines, and our reply-subject inputs are bounded by the
// helpdesk.ticket schema's max_length 200 anyway.
func writeHeader(b *strings.Builder, name, value string) {
	b.WriteString(name)
	b.WriteString(": ")
	b.WriteString(value)
	b.WriteString("\r\n")
}

// formatReferences turns the parsed References slice back into
// the RFC-5322 space-separated angle-bracketed wire form. Each
// entry has its angle brackets stripped on parse and re-added
// here so the output is well-formed regardless of input quirks.
func formatReferences(refs []string) string {
	var b strings.Builder
	for i, r := range refs {
		if i > 0 {
			b.WriteByte(' ')
		}
		b.WriteByte('<')
		b.WriteString(strings.Trim(r, "<>"))
		b.WriteByte('>')
	}
	return b.String()
}

// normaliseBodyEOL converts bare \n in user-supplied bodies to
// \r\n. RFC-5322 §2.3 mandates CRLF; some agents copy-paste from
// text editors that emit LF only, and the MTA may or may not
// canonicalise on its end.
func normaliseBodyEOL(s string) string {
	// Replace \r\n with a placeholder, then \n → \r\n, then
	// restore. This avoids the \r → \r\r\n bug a naive
	// double-replace would hit.
	s = strings.ReplaceAll(s, "\r\n", "\x00")
	s = strings.ReplaceAll(s, "\n", "\r\n")
	s = strings.ReplaceAll(s, "\x00", "\r\n")
	return s
}

// generateMessageID produces a globally-unique RFC-5322
// Message-ID using 16 random bytes + the configured domain. The
// format `<hex32@domain>` mirrors what mailing-list software
// (Mailman, Discourse) emits. The angle brackets are added by the
// caller writing the header so this returns the bare id.
func generateMessageID(domain string) (string, error) {
	var buf [16]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf[:]) + "@" + strings.TrimSpace(domain), nil
}

// generateBoundary produces a multipart boundary that's
// guaranteed unique within this message and unlikely to collide
// with body content. 12 hex chars + a static prefix is plenty.
func generateBoundary() (string, error) {
	var buf [12]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return "kapp-helpdesk-" + hex.EncodeToString(buf[:]), nil
}
