-- Phase K — Stock move reversal.
--
-- Adds a `reversal_of` BIGINT column to inventory_moves so a
-- correction (contra) entry can carry an explicit pointer back to
-- the move it reverses. Because inventory_moves is append-only and
-- already RLS-scoped per tenant, ReverseMove just inserts a fresh
-- opposite-sign row referencing the original — never mutates the
-- original. Reference: frappe/erpnext Stock Entry cancellation.
--
-- The column is nullable: existing moves never have a reversal
-- target, and a non-reversal move (a fresh receipt or delivery)
-- continues to leave it null. A partial unique index prevents the
-- same move from being reversed twice — the first contra-entry wins,
-- subsequent attempts collide at 23505 and the Go layer surfaces
-- ErrAlreadyReversed.

ALTER TABLE inventory_moves
    ADD COLUMN IF NOT EXISTS reversal_of BIGINT;

CREATE UNIQUE INDEX IF NOT EXISTS inventory_moves_reversal_of_uniq
    ON inventory_moves (tenant_id, reversal_of)
    WHERE reversal_of IS NOT NULL;

CREATE INDEX IF NOT EXISTS inventory_moves_reversal_of_idx
    ON inventory_moves (tenant_id, reversal_of)
    WHERE reversal_of IS NOT NULL;

COMMENT ON COLUMN inventory_moves.reversal_of IS
    'When set, this row is a contra-entry generated by ReverseMove that exactly cancels the move with id = reversal_of. Append-only: original moves are never mutated.';
