-- Phase B3 — Marketplace runtime engine schema
--
-- Extends the B2 catalog (000068) with the FIVE runtime-tracking
-- tables the engine needs to drive install / invoke / uninstall:
--
--   1. marketplace_extension_ktypes
--      One row per extension-authored KType registered for a given
--      install. Cascades on installation delete so an uninstall
--      cleanly removes every ext.publisher.name KType the extension
--      brought in (extension KTypes live alongside platform KTypes
--      in the krecords table but are isolated to the installation
--      that registered them).
--
--   2. marketplace_extension_workflows
--      Same shape for state-machine definitions. The platform's
--      built-in `workflows` table predates RLS-by-FORCE so we use
--      a separate table for extension-authored workflows to keep
--      the FORCE-RLS posture B2 introduced for installations
--      uniform across the marketplace surface.
--
--   3. marketplace_extension_agent_tools
--      Agent-tool descriptors with handler/endpoint/timeout/retry
--      MATERIALIZED as columns (not just stored as JSONB inside
--      the descriptor blob) so the runtime dispatcher does a single
--      indexed point-read per invoke instead of re-parsing the
--      manifest. The descriptor JSON is preserved as well for the
--      agent platform's introspection surfaces (B4) — the
--      materialised columns are an index, not the source of truth.
--
--   4. marketplace_webhook_subscriptions
--      One row per `webhooks_consumed[]` entry in the manifest.
--      The B4 event-router will SELECT from this table on every
--      drain tick (same shape as the platform's existing
--      `webhooks` table from 000024) — the marketplace table is
--      kept separate so the runtime audit + cascade semantics
--      stay aligned with the rest of the extension surface.
--
--   5. marketplace_dispatch_log
--      Append-only audit log of every outbound HMAC POST the
--      runtime sends (tool invokes + lifecycle hooks). Survives
--      installation deletion via ON DELETE SET NULL on
--      installation_id so post-uninstall the log is still
--      readable for forensics. Indexed by (tenant_id, request_id)
--      so a single invocation's retry attempts can be grouped
--      with one query.
--
-- ALSO adds the per-install HMAC signing secret column to
-- marketplace_extension_installations. The secret is 32 random
-- bytes (base64url-encoded → 43 chars + no padding) generated by
-- the engine at install time. The reverse direction — extension's
-- webhook server verifying the signature on incoming requests —
-- uses this same secret.
--
-- Conventions matching 000068:
--   * tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
--   * ENABLE ROW LEVEL SECURITY + FORCE ROW LEVEL SECURITY
--   * tenant_isolation policy keyed off current_setting('app.tenant_id')
--   * GRANT SELECT/INSERT/UPDATE/DELETE to kapp_app

-- ---------------------------------------------------------------
-- Signing secret on installations
-- ---------------------------------------------------------------

-- The signing secret is base64url, no padding, 32 bytes of entropy
-- → 43 chars. NOT NULL with a sentinel default so existing test-
-- harness installations (created via direct SQL in the integration
-- tests of B2) keep working. The runtime regenerates the secret on
-- every install via runtime.Engine.Install so the default is only
-- ever observed by tests that bypass the engine.
ALTER TABLE marketplace_extension_installations
    ADD COLUMN IF NOT EXISTS signing_secret TEXT NOT NULL DEFAULT '';

-- After application code (B3+) populates the column on every new
-- install, future migrations may drop the default. We keep it for
-- this migration because some integration-test fixtures predate B3
-- and insert directly into the table.
--
-- ADD CONSTRAINT does not have an IF NOT EXISTS form; we wrap in a
-- DO block so re-running the migration (e.g. after a previous
-- partial failure on a later statement) is a no-op rather than
-- erroring with 42710 "constraint already exists".
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'marketplace_installations_signing_secret_format_chk'
    ) THEN
        ALTER TABLE marketplace_extension_installations
            ADD CONSTRAINT marketplace_installations_signing_secret_format_chk
            CHECK (
                signing_secret = ''
                OR signing_secret ~ '^[A-Za-z0-9_-]{43}$'
            );
    END IF;
END $$;

-- ---------------------------------------------------------------
-- 1. marketplace_extension_ktypes
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS marketplace_extension_ktypes (
    tenant_id        UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    installation_id  UUID NOT NULL REFERENCES marketplace_extension_installations(id) ON DELETE CASCADE,
    ktype_name       TEXT NOT NULL,
    ktype_version    INTEGER NOT NULL DEFAULT 1,
    schema           JSONB NOT NULL,
    registered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, installation_id, ktype_name),

    -- Extension KType names live in the ext.<publisher>.<slug>
    -- namespace per EXTENSION_SPEC §4. The DB CHECK mirrors the
    -- Go-side regex in internal/marketplace/manifest.go so
    -- malformed names cannot reach the table via a direct INSERT
    -- (e.g. from a future ops script that bypasses the engine).
    CONSTRAINT marketplace_ext_ktypes_name_chk
        CHECK (ktype_name ~ '^ext\.[a-z][a-z0-9_-]*\.[a-z][a-z0-9_]*$'),
    CONSTRAINT marketplace_ext_ktypes_version_positive_chk
        CHECK (ktype_version >= 1)
);

CREATE INDEX IF NOT EXISTS marketplace_ext_ktypes_install_idx
    ON marketplace_extension_ktypes (tenant_id, installation_id);

ALTER TABLE marketplace_extension_ktypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_extension_ktypes FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_extension_ktypes_isolation
    ON marketplace_extension_ktypes;
CREATE POLICY marketplace_extension_ktypes_isolation
    ON marketplace_extension_ktypes
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON marketplace_extension_ktypes TO kapp_app;

-- ---------------------------------------------------------------
-- 2. marketplace_extension_workflows
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS marketplace_extension_workflows (
    tenant_id        UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    installation_id  UUID NOT NULL REFERENCES marketplace_extension_installations(id) ON DELETE CASCADE,
    workflow_name    TEXT NOT NULL,
    workflow_version INTEGER NOT NULL DEFAULT 1,
    definition       JSONB NOT NULL,
    registered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, installation_id, workflow_name),

    CONSTRAINT marketplace_ext_workflows_version_positive_chk
        CHECK (workflow_version >= 1)
);

CREATE INDEX IF NOT EXISTS marketplace_ext_workflows_install_idx
    ON marketplace_extension_workflows (tenant_id, installation_id);

ALTER TABLE marketplace_extension_workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_extension_workflows FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_extension_workflows_isolation
    ON marketplace_extension_workflows;
CREATE POLICY marketplace_extension_workflows_isolation
    ON marketplace_extension_workflows
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON marketplace_extension_workflows TO kapp_app;

-- ---------------------------------------------------------------
-- 3. marketplace_extension_agent_tools
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS marketplace_extension_agent_tools (
    tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    installation_id     UUID NOT NULL REFERENCES marketplace_extension_installations(id) ON DELETE CASCADE,
    tool_name           TEXT NOT NULL,
    descriptor          JSONB NOT NULL,
    handler             TEXT NOT NULL,
    endpoint            TEXT NOT NULL,
    timeout_ms          INTEGER NOT NULL,
    retry_max_attempts  INTEGER NOT NULL,
    retry_backoff       TEXT NOT NULL,
    registered_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, installation_id, tool_name),

    -- handler enum mirrors the manifest's accepted values. wasm
    -- is reserved for Phase 2 — the runtime rejects it until then.
    CONSTRAINT marketplace_ext_agent_tools_handler_chk
        CHECK (handler IN ('webhook')),
    -- endpoint MUST be https — same rule as installations.webhook_base.
    CONSTRAINT marketplace_ext_agent_tools_endpoint_https_chk
        CHECK (endpoint ~ '^https://'),
    CONSTRAINT marketplace_ext_agent_tools_timeout_positive_chk
        CHECK (timeout_ms > 0 AND timeout_ms <= 30000),
    CONSTRAINT marketplace_ext_agent_tools_attempts_chk
        CHECK (retry_max_attempts >= 1 AND retry_max_attempts <= 5),
    CONSTRAINT marketplace_ext_agent_tools_backoff_chk
        CHECK (retry_backoff IN ('linear', 'exponential'))
);

CREATE INDEX IF NOT EXISTS marketplace_ext_agent_tools_install_idx
    ON marketplace_extension_agent_tools (tenant_id, installation_id);

ALTER TABLE marketplace_extension_agent_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_extension_agent_tools FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_extension_agent_tools_isolation
    ON marketplace_extension_agent_tools;
CREATE POLICY marketplace_extension_agent_tools_isolation
    ON marketplace_extension_agent_tools
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON marketplace_extension_agent_tools TO kapp_app;

-- ---------------------------------------------------------------
-- 4. marketplace_webhook_subscriptions
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS marketplace_webhook_subscriptions (
    id                UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id         UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    installation_id   UUID NOT NULL REFERENCES marketplace_extension_installations(id) ON DELETE CASCADE,
    event             TEXT NOT NULL,
    filter            JSONB NOT NULL DEFAULT '{}'::jsonb,
    endpoint          TEXT NOT NULL,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, id),

    -- event names follow the kapp event-bus convention (lowercase
    -- dotted segments). Same shape the workflow engine uses for
    -- emit_event / on_event hooks.
    CONSTRAINT marketplace_webhook_subs_event_chk
        CHECK (event ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$'),
    CONSTRAINT marketplace_webhook_subs_endpoint_https_chk
        CHECK (endpoint ~ '^https://')
);

CREATE INDEX IF NOT EXISTS marketplace_webhook_subs_install_idx
    ON marketplace_webhook_subscriptions (tenant_id, installation_id);

-- Lookup index for the B4 router: given an event-type, find every
-- subscription. The router scans this on each drain tick.
CREATE INDEX IF NOT EXISTS marketplace_webhook_subs_event_idx
    ON marketplace_webhook_subscriptions (tenant_id, event);

ALTER TABLE marketplace_webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_webhook_subscriptions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_webhook_subscriptions_isolation
    ON marketplace_webhook_subscriptions;
CREATE POLICY marketplace_webhook_subscriptions_isolation
    ON marketplace_webhook_subscriptions
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON marketplace_webhook_subscriptions TO kapp_app;

-- ---------------------------------------------------------------
-- 5. marketplace_dispatch_log
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS marketplace_dispatch_log (
    id                  UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- SET NULL so the audit row survives uninstall. The
    -- (extension_id, version_id) tuple is also captured so an
    -- ops tool can correlate after the installation row goes
    -- away.
    installation_id     UUID REFERENCES marketplace_extension_installations(id) ON DELETE SET NULL,
    extension_id        UUID NOT NULL,
    extension_version_id UUID NOT NULL,
    kind                TEXT NOT NULL,
    endpoint            TEXT NOT NULL,
    request_id          UUID NOT NULL,
    attempt             INTEGER NOT NULL,
    -- Body hash, not body. Audit log is high-volume; the operator
    -- can re-execute against the live extension if the body is
    -- needed for replay-debugging. Hash is enough for forensics
    -- ("did we dispatch THIS payload?").
    request_body_sha256 TEXT NOT NULL,
    signature           TEXT NOT NULL,
    response_status     INTEGER,
    response_latency_ms INTEGER,
    error               TEXT,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ,

    PRIMARY KEY (tenant_id, id),

    CONSTRAINT marketplace_dispatch_log_kind_chk
        CHECK (kind IN (
            'tool_invoke',
            'lifecycle_pre_install',
            'lifecycle_post_install',
            'lifecycle_pre_uninstall',
            'lifecycle_post_uninstall',
            'event_delivery',
            'health_check'
        )),
    CONSTRAINT marketplace_dispatch_log_attempt_positive_chk
        CHECK (attempt >= 1),
    CONSTRAINT marketplace_dispatch_log_body_sha256_chk
        CHECK (request_body_sha256 ~ '^[0-9a-f]{64}$'),
    -- Either we have a response status OR we have an error. Both
    -- can be present (HTTP 502 with the underlying TCP-reset
    -- error text). Neither isn't allowed once completed_at is
    -- set; while completed_at is NULL the row is the in-flight
    -- attempt and both columns are NULL.
    CONSTRAINT marketplace_dispatch_log_completion_consistent_chk
        CHECK (
            (completed_at IS NULL AND response_status IS NULL AND error IS NULL AND response_latency_ms IS NULL)
            OR (completed_at IS NOT NULL AND (response_status IS NOT NULL OR error IS NOT NULL))
        )
);

-- Group all attempts for one logical dispatch (e.g. retry trail).
CREATE INDEX IF NOT EXISTS marketplace_dispatch_log_request_idx
    ON marketplace_dispatch_log (tenant_id, request_id, attempt);

-- Recent-failure lookup for the health check surface.
CREATE INDEX IF NOT EXISTS marketplace_dispatch_log_failure_idx
    ON marketplace_dispatch_log (tenant_id, installation_id, started_at DESC)
    WHERE response_status IS NOT NULL AND response_status >= 400;

ALTER TABLE marketplace_dispatch_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_dispatch_log FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_dispatch_log_isolation
    ON marketplace_dispatch_log;
CREATE POLICY marketplace_dispatch_log_isolation
    ON marketplace_dispatch_log
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE ON marketplace_dispatch_log TO kapp_app;
-- Deliberately NO DELETE: dispatch log is append-only audit.
-- Retention is handled by a future SQL function + scheduled job,
-- not by the application layer.
