// Payroll extends the Phase E HR catalog with the two KTypes needed to
// model a compensation structure — salary components (earnings and
// deductions) and the per-employee salary structure that references
// them. Keeping these next to the rest of hr.go means the web UI, the
// KChat bridge, and the agent-tool layer all drive off the same
// metadata file.
//
// The KTypes are intentionally declarative-only: there is no payroll
// run engine yet (that's a Phase H+ deliverable). The structure gives
// the AR / HR report builder something to aggregate against and gives
// the importer a stable target for migrating ERPNext/HRMS Salary
// Slip / Salary Structure rows into Kapp.
package hr

import "github.com/kennguy3n/kapp-fab/internal/ktype"

const (
	KTypeSalaryComponent = "hr.salary_component"
	KTypeSalaryStructure = "hr.salary_structure"
	KTypePayslip         = "hr.payslip"
	KTypePayRun          = "hr.pay_run"
)

// salaryComponentSchema — reusable earning/deduction definition. A
// component has an `amount_type` of fixed or percentage; when
// percentage, the `amount` is interpreted as a % of base_salary on
// the referencing structure.
var salaryComponentSchema = []byte(`{
  "name": "hr.salary_component",
  "version": 1,
  "fields": [
    {"name": "code", "type": "string", "required": true, "max_length": 64},
    {"name": "name", "type": "string", "required": true, "max_length": 200},
    {"name": "type", "type": "enum", "values": ["earning", "deduction"], "required": true},
    {"name": "amount_type", "type": "enum", "values": ["fixed", "percentage"], "required": true, "default": "fixed"},
    {"name": "amount", "type": "number", "min": 0, "required": true},
    {"name": "currency", "type": "string", "pattern": "^[A-Z]{3}$", "default": "USD"},
    {"name": "taxable", "type": "boolean", "default": true},
    {"name": "active", "type": "boolean", "default": true}
  ],
  "views": {
    "list": {"columns": ["code", "name", "type", "amount_type", "amount", "currency", "active"]},
    "form": {"sections": [{"title": "Component", "fields": ["code", "name", "type", "amount_type", "amount", "currency", "taxable", "active"]}]}
  },
  "cards": {"summary": "{{code}} — {{name}} ({{type}}, {{amount_type}} {{amount}})"},
  "permissions": {"read": ["tenant.member"], "write": ["hr.admin", "tenant.admin"]}
}`)

// salaryStructureSchema — per-employee compensation bundle. The
// `components` array is a list of {component_id, override_amount,
// override_amount_type} entries so a structure can reuse the standard
// catalog while still allowing per-employee adjustments.
var salaryStructureSchema = []byte(`{
  "name": "hr.salary_structure",
  "version": 1,
  "fields": [
    {"name": "employee_id", "type": "ref", "ktype": "hr.employee", "required": true},
    {"name": "effective_from", "type": "date", "required": true},
    {"name": "effective_until", "type": "date"},
    {"name": "currency", "type": "string", "pattern": "^[A-Z]{3}$", "default": "USD"},
    {"name": "base_salary", "type": "number", "min": 0, "required": true},
    {"name": "payment_frequency", "type": "enum", "values": ["monthly", "biweekly", "weekly"], "default": "monthly"},
    {"name": "components", "type": "array"},
    {"name": "status", "type": "enum", "values": ["draft", "active", "archived"], "default": "draft"}
  ],
  "views": {
    "list": {"columns": ["employee_id", "effective_from", "effective_until", "base_salary", "currency", "status"]},
    "form": {"sections": [
      {"title": "Structure", "fields": ["employee_id", "effective_from", "effective_until", "currency", "base_salary", "payment_frequency"]},
      {"title": "Components", "fields": ["components"]},
      {"title": "Lifecycle", "fields": ["status"]}
    ]}
  },
  "cards": {"summary": "{{employee_id}} — {{base_salary}} {{currency}} / {{payment_frequency}} ({{status}})"},
  "permissions": {"read": ["tenant.member"], "write": ["hr.admin", "tenant.admin"]}
}`)

// payslipSchema — one row per (employee, pay_period). Generated by
// the payroll engine off the employee's salary_structure; the
// `earnings` and `deductions` arrays carry resolved component lines
// so the slip is self-contained even after the underlying
// component/structure mutates.
var payslipSchema = []byte(`{
  "name": "hr.payslip",
  "version": 1,
  "fields": [
    {"name": "pay_run_id", "type": "ref", "ktype": "hr.pay_run"},
    {"name": "employee_id", "type": "ref", "ktype": "hr.employee", "required": true},
    {"name": "pay_period_start", "type": "date", "required": true},
    {"name": "pay_period_end", "type": "date", "required": true},
    {"name": "structure_id", "type": "ref", "ktype": "hr.salary_structure"},
    {"name": "currency", "type": "string", "pattern": "^[A-Z]{3}$", "default": "USD"},
    {"name": "earnings", "type": "array"},
    {"name": "deductions", "type": "array"},
    {"name": "gross_pay", "type": "number", "min": 0},
    {"name": "total_deductions", "type": "number", "min": 0},
    {"name": "net_pay", "type": "number"},
    {"name": "journal_entry_id", "type": "string"},
    {"name": "status", "type": "enum", "values": ["draft", "submitted", "approved", "paid", "cancelled"], "default": "draft"}
  ],
  "views": {
    "list": {"columns": ["employee_id", "pay_period_start", "pay_period_end", "gross_pay", "total_deductions", "net_pay", "currency", "status"]},
    "form": {"sections": [
      {"title": "Header", "fields": ["employee_id", "pay_run_id", "structure_id", "pay_period_start", "pay_period_end", "currency", "status"]},
      {"title": "Earnings", "fields": ["earnings"]},
      {"title": "Deductions", "fields": ["deductions"]},
      {"title": "Totals", "fields": ["gross_pay", "total_deductions", "net_pay", "journal_entry_id"]}
    ]}
  },
  "cards": {"summary": "{{employee_id}} — {{pay_period_start}}..{{pay_period_end}} (net {{net_pay}} {{currency}})"},
  "permissions": {"read": ["tenant.member"], "write": ["hr.admin", "tenant.admin"]}
}`)

// payRunSchema — the parent batch for a tenant payroll cycle. Wraps
// many payslips, exposes the optional department filter that scopes
// generation, and tracks the rollup totals shown in the UI.
var payRunSchema = []byte(`{
  "name": "hr.pay_run",
  "version": 1,
  "fields": [
    {"name": "name", "type": "string", "required": true, "max_length": 200},
    {"name": "pay_period_start", "type": "date", "required": true},
    {"name": "pay_period_end", "type": "date", "required": true},
    {"name": "department", "type": "string"},
    {"name": "currency", "type": "string", "pattern": "^[A-Z]{3}$", "default": "USD"},
    {"name": "payslip_count", "type": "integer", "min": 0, "default": 0},
    {"name": "total_gross", "type": "number", "default": 0},
    {"name": "total_net", "type": "number", "default": 0},
    {"name": "salary_expense_account_code", "type": "string"},
    {"name": "salary_payable_account_code", "type": "string"},
    {"name": "journal_entry_id", "type": "string"},
    {"name": "status", "type": "enum", "values": ["draft", "processing", "submitted", "approved", "paid"], "default": "draft"}
  ],
  "views": {
    "list": {"columns": ["name", "pay_period_start", "pay_period_end", "department", "payslip_count", "total_gross", "total_net", "currency", "status"]},
    "form": {"sections": [
      {"title": "Run", "fields": ["name", "pay_period_start", "pay_period_end", "department", "currency", "status"]},
      {"title": "Totals", "fields": ["payslip_count", "total_gross", "total_net"]},
      {"title": "Posting", "fields": ["salary_expense_account_code", "salary_payable_account_code", "journal_entry_id"]}
    ]}
  },
  "cards": {"summary": "{{name}} — {{pay_period_start}}..{{pay_period_end}} ({{status}})"},
  "permissions": {"read": ["tenant.member"], "write": ["hr.admin", "tenant.admin"]},
  "agent_tools": ["hr.generate_payslips", "hr.post_pay_run"]
}`)

// PayrollKTypes returns the payroll surface as a freshly-constructed
// slice so callers can register it alongside (or independently of) the
// Phase E HR catalog. hr.All() does NOT include these so existing
// deployments are unaffected until their registration flow opts in.
func PayrollKTypes() []ktype.KType {
	return []ktype.KType{
		{Name: KTypeSalaryComponent, Version: 1, Schema: salaryComponentSchema},
		{Name: KTypeSalaryStructure, Version: 1, Schema: salaryStructureSchema},
		{Name: KTypePayslip, Version: 1, Schema: payslipSchema},
		{Name: KTypePayRun, Version: 1, Schema: payRunSchema},
	}
}
